apiVersion: v1
kind: Service
metadata:
  name: morphling-ui
  namespace: morphling-system
  labels:
    app: morphling
    component: ui
spec:
  type: NodePort
  ports:
    - port: 9091
      protocol: TCP
      name: ui
      targetPort: 9091
  selector:
    app: morphling
    component: ui
