
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - morphling.kubedl.io
  resources:
  - profilingexperiments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - morphling.kubedl.io
  resources:
  - profilingexperiments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - morphling.kubedl.io
  resources:
  - trials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - morphling.kubedl.io
  resources:
  - trials/status
  verbs:
  - get
  - patch
  - update
