# permissions for end users to view trials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trial-viewer-role
rules:
- apiGroups:
  - morphling.kubedl.io
  resources:
  - trials
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - morphling.kubedl.io
  resources:
  - trials/status
  verbs:
  - get
