apiVersion: v1
kind: Service
metadata:
  name: morphling-algorithm-server
  namespace: morphling-system
  labels:
    {{- include "morphling.labels" . | nindent 4 }}
spec:
  ports:
    - name: morphling-api
      port: 9996
      protocol: TCP
      targetPort: 9996
  selector:
    deployment: morphling-algorithm-server
  type: NodePort