apiVersion: v1
kind: Service
metadata:
  name: morphling-algorithm-server
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: morphling-api
      port: 9996
      protocol: TCP
      targetPort: 9996
  selector:
    deployment: morphling-algorithm-server
  type: NodePort