apiVersion: morphling.kubedl.io/v1alpha1
kind: Trial
metadata:
  labels:
    experiment: mobilenet-experiment-grid-1
  name: mobilenet-experiment-grid-1-bz8glvnm
spec:
  clientTemplate:
    metadata: {}
    spec:
      backoffLimit: 1
      template:
        metadata: {}
        spec:
          containers:
            - args:
                - morphling_client.py
                - --model
                - mobilenet
                - --printLog
                - "True"
                - --num_tests
                - "10"
              command:
                - python3
              env:
                - name: TF_CPP_MIN_LOG_LEVEL
                  value: "3"
                - name: MODEL_NAME
                  value: mobilenet
              image: kubedl/morphling-http-client:demo
              imagePullPolicy: IfNotPresent
              name: pi
              resources:
                limits:
                  cpu: 800m
                  memory: 1800Mi
                requests:
                  cpu: 800m
                  memory: 1800Mi
          restartPolicy: Never
  objective:
    objectiveMetricName: qps
    type: maximize
  samplingResult:
    - category: env
      name: BATCH_SIZE
      value: "1"
    - category: resource
      name: cpu
      value: 2000m
    - category: resource
      name: memory
      value: 2000Mi
  servicePodTemplate:
    metadata: {}
    template:
      metadata: {}
      spec:
        containers:
          - env:
              - name: MODEL_NAME
                value: mobilenet
            image: kubedl/morphling-tf-model:demo
            imagePullPolicy: IfNotPresent
            name: resnet-container
            ports:
              - containerPort: 8500
                protocol: TCP
            resources:
              limits:
                cpu: "1"
                memory: 1800Mi
              requests:
                cpu: "1"
                memory: 1800Mi
