apiVersion: v1
kind: Service
metadata:
  name: morphling-ui-lb
  namespace: morphling-system
  labels:
    app: morphling
    component: ui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: ui
      targetPort: 9091
  selector:
    app: morphling
    component: ui
