apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: morphling-mysql-secrets
  namespace: morphling-system
  labels:
    {{- include "morphling.labels" . | nindent 4 }}
data:
  MYSQL_ROOT_PASSWORD: dGVzdA== # "test"
