apiVersion: v1
kind: Service
metadata:
  name: morphling-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    app: morphling
    component: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
      name: dbapi
  selector:
    app: morphling
    component: mysql
