apiVersion: v1
kind: PersistentVolume
metadata:
  name: morphling-mysql
  labels:
    type: local
    app: morphling
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/morphling
