apiVersion: v1
kind: PersistentVolume
metadata:
  name: morphling-mysql
  labels:
    type: local
    app: morphling
    {{- include "morphling.labels" . | nindent 4 }}
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/morphling
