apiVersion: v1
kind: Service
metadata:
  name: morphling-algorithm-server
  namespace: morphling-system
spec:
  ports:
    - name: morphling-api
#      nodePort: 6789
      port: 9996
      protocol: TCP
      targetPort: 9996
  selector:
    deployment: morphling-algorithm-server
  type: NodePort